version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - my_network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: BBDDuniversitat
      MYSQL_USER: rmihailescu22
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  auxiliary:
    image: alpine
    volumes:
      - aux_data:/data
    networks:
      - my_network

volumes:
  db_data:
  web_data:
  aux_data:

networks:
  my_network:

